services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-gluetun_server_1
      APP_PORT: 3003

  server:
    image: lakker/pulsarr:latest
    network_mode: "container:martinmeel-gluetun_server_1"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/.env:/app/.env
    environment:
      - PUID=1000
      - PGID=1000
    # Your timezone
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    stop_grace_period: 1m

