services:
  app_proxy:
    environment:
      APP_HOST: martinmeel-DIR Name_server/web/db_1
      APP_PORT: 1234
      #PROXY_AUTH_WHITELIST: "/api/*"

  server or web or db...:
    image: host/image:4.0.16
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/dir1/dir2:/in app directory
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 1234:1234
    restart: unless-stopped
    stop_grace_period: 1m